[libraries.movies]
directory = "/home/omzet/Movies"
workflow = "movies"


[[workflows]]
name = "movies"
scratchpad_directory = "/tmp/omzet/cache"
included_extensions = ["mkv", "mp4"]
tasks = ["h265_encoder", "skipped_example_task"]


[[tasks]]
id = "h265_encoder"
description = "Encodes the file to be H265"
probe = '''
    CODEC=$(ffprobe "$OMZET_INPUT" -show_entries stream=codec_name -select_streams v:0 -of compact=p=0:nk=1 -v 0)

    echo "$CODEC"
    if [ "$CODEC" == "hevc" ]; then
        exit 1 # an exit code "1" indicates that the task is not necessary
    else
        exit 0
    fi
'''
command = '''
    echo "input: $OMZET_INPUT"
    echo "output: $OMZET_OUTPUT"

    ffmpeg -i $OMZET_INPUT -c:v libx265 -c:a copy -t 5 $OMZET_OUTPUT
'''

[[tasks]]
id = "skipped_example_task"
description = "A task that will always be skipped because of its exit code in the probe"
probe = "exit 1"
command = '''
    echo "this will never be printed"
'''

[[tasks]]
id = "always_running_task"
description = "A task that will always run, because there is no probe"
command = '''
    echo "this will always be printed"
'''

