[package]
name = "omzet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
run_script = "0.11.0"
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = {version = "0.3.19", features = ["std", "env-filter"]}
uuid = { version = "1.16.0", features = [ "v4" ] }
